image: Visual Studio 2017

branches:
  only:
    - master

skip_tags: true
max_jobs: 1

clone_folder: C:\Projects\ILSpyTextSmoothing

init:
  - git config --global core.autocrlf false

shallow_clone: true

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  GITHUB_API_TOKEN:
    secure: uSAWwQ1dP/pvqqTxqyqphIP8c1gZFvc4BKudT6ZWKCERPGFiMaO0Si3zeh++hXyJ

matrix:
  fast_finish: true

cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

install:
  - cmd: powershell.exe -NoProfile -NonInteractive -NoLogo -File Build.ps1

build_script:
  - cmd: dotnet.exe build -c Release C:\Projects\ILSpyTextSmoothing\ILSpyTextSmoothing\ILSpyTextSmoothing-CI.csproj

artifacts:
  - path: C:\Projects\ILSpyTextSmoothing\ILSpyTextSmoothing\bin\Release\net46\ILSpyTextSmoothing.Plugin.dll
    name: Plugin
