// <auto-generated></auto-generated>

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("ILSpyTextSmoothing")]
[assembly: AssemblyDescription("Makes text view fonts glossy and smooth.")]
[assembly: AssemblyConfiguration("Private")]
[assembly: AssemblyCompany("George Chakhidze")]
[assembly: AssemblyProduct("ILSpyTextSmoothing")]
[assembly: AssemblyCopyright("Copyright © 2018 George Chakhidze")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("1F450464-B467-4C0F-8593-686073063BB7")]
[assembly: AssemblyVersion("1.3.0.0")]
[assembly: AssemblyFileVersion("1.3.0.0")]
[assembly: AssemblyInformationalVersion("1.3.0.0")]
