// <auto-generated></auto-generated>

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("ILSpyTextSmoothing")]
[assembly: AssemblyDescription("Makes text view fonts glossy and smooth.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("ILSpyTextSmoothing")]
[assembly: AssemblyCopyright("Copyright © 2018 George Chakhidze")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("1f450464-b467-4c0f-8593-686073063bb7")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
